package com.javatramp.Lesson1.Task1.exception;

public enum ErrorCode {
    OUT_OF_RANGE_DEGREES_VALUE, UNAVAILABLE_TAKE_OFF, UNAVAILABLE_TAKE_OFF_DUE_TO_PASSENGERS_QUANTITY, UNAVAILABLE_TAKE_OFF_DUE_TO_CARRYING_CAPACITY_EXCESS, UNAVAILABLE_LANDING
}
